### ISSUE TITLE
"Schrödinger's" Inference

### ISSUE THREAD

**Issue by will-ball** [r-causal/causal-inference-in-R#191]
Hi Lucy and Malcolm - first of all fantastic resource. I've already found reading this work useful so hats off for your efforts.

This isn't a particularly substantive point about content really, but rather a question of framing. The issue of ambiguous causal language & denials of causality in reporting observational studies is really important. I know it's often characterised as 'Schrödinger's' inference, but I think it's worth raising that Erwin Schrödinger isn't a benign individual to reference and it may be better to avoid doing so in future.

There's been [growing recognition of his problematic behaviour](https://archive.ph/Q06rJ) in recent years, and academic institutions have taken steps to [distance themselves from his personal legacy](https://archive.ph/I15U5).

Of course I leave it up to you.

Thanks,
Will

**Comment by LucyMcGowan** [comment]
for what it is worth, I think I like your last option! I am obviously partial to the term "casual" inference but also think it fits nicely here. Makes sense that we can leave the quote as is, since that is what was said.

**Comment by malcolmbarrett** [comment]
It's an inexact analogy, anyway, so maybe that's better from a writing perspective as well, although I do appreciate having a term to succinctly refer to the problem of doing but denying causal inference

**Comment by malcolmbarrett** [comment]
"Causal Denial" 😆

**Comment by will-ball** [comment]
Thanks for taking this on board - absolutely happy for you to keep the quote and I take your point about this being different from naming a building after the man.

I sometimes liken it to 'having your cake and eating it too', although there's no snappy way to refer to that.
