### ISSUE TITLE
Caption for Figure 6.6

### ISSUE THREAD

**Issue by nikhilpatelmd** [r-causal/causal-inference-in-R#227]
Hi there! 

I believe the caption for Figure 6.6 has a typo. It states: "In the third dataset, covariate is a mediator, and we should control for it if we want the total effect, but not if we want the direct effect."

Later on, when discussing adjusting for mediators in Figure 6.7c, the caption states "We should adjust for covariate if we want the direct effect, but not if we want the total effect."

I think the caption for Figure 6.7c is correct and the previous one is a typo? It was a little confusing for me at first so I figured I would let you know and make sure I understood correctly!

![Screenshot from 2024-02-12 16-21-01](https://github.com/r-causal/causal-inference-in-R/assets/76622984/c7b3182a-7e6d-4e67-95f6-e057c003b166)

**Comment by malcolmbarrett** [comment]
You are correct, thank you!
