### ISSUE TITLE
"10  Evaluating your propensity score model"

### ISSUE THREAD

**Issue by ChunRuChien** [r-causal/causal-inference-in-R#231]
its content looks the same as in "9 Using the propensity score" ?

**Comment by malcolmbarrett** [comment]
Thank you for pointing this out. It looks like there was a mixup in one of the recent chapter refactors that overrode ch 9 with the content from ch 10. I will fix this ASAP

Note to self: it happened around this renaming so should be recoverable from there: https://github.com/r-causal/causal-inference-in-R/commits/542588fd6f1c3b6b6fa4af58058a0ce8c6648755/chapters/chapter-09.qmd?browsing_rename_history=true&new_path=chapters/09-using-ps.qmd&original_branch=main
