### ISSUE TITLE
Explicitly state DAG includes all (relevant) paths

### ISSUE THREAD

**Issue by LucyMcGowan** [r-causal/causal-inference-in-R#237]
Maybe a box in the DAG chapter saying something like:

>In its purest form, a DAG represents the full causal structure for variables of interest. That is, if only one arrow enters a variable, that means that variable is fully explained by only the factor on the other end, if two arrows enter a variable, the variable is fully explained by only the two factors on the other end of the two arrows, and so on. In practice, DAGs must at least capture all of the paths that could impact the causal estimand of interest.

**Comment by malcolmbarrett** [comment]
I think a better way to do this is to show what happens when you misspecify a dag. I'm imagining a short addition, maybe a paragraph and a side by side image of the true dag and a misspecified version and what happens when you simulate and run the misspecified adjustment set
