### ISSUE TITLE
Minor typos in chapter 3

### ISSUE THREAD

**Issue by rpruim** [r-causal/causal-inference-in-R#283]
From Chapter 3:

* [ ] defined at a particular **instance** in time -> Do you mean *instant*?
* [ ] I'm not a fan of overusing `data` for data frame (`df` is worse, since there is also a function by that name).  Even for toy examples, I prefer a descriptive name.  I'd reserve `data` only for "generic" examples and pseudo-code.  Example: For the chocolate/vanilla ice cream example, I'd prefer a name like `icecream` or `icecream_happiness`.  That's especially nice when encountering code chunks that reference `data` that has been defined in some other chunk.
* [ ] As a sneak peak, our issue here **was that how** the exposure was decided, if instead we randomized who ate chocolate versus vanilla ice cream we would (on average, with a large enough sample) recover the true causal effect. --> delete *that*.
*  [ ] You can see how this **falls under consistency** --> You can see how this violates consistency
*  [ ] One of the main ways to combat interference **is change** the unit under consideration. --> is *to* change
*  [ ] Following any of the recipes in this book **are** unlikely to give valid answers if the causal assumptions are badly violated. -> *is* unlikely (Following is he subject of the sentence) or delete "Following any of" so that recipes becomes the subject.

Is it useful to record minor typos here (or somewhere else)?  Is it useful to have a separate issue per chapter?  If useful, I'll try to record things as I spot them.

**Comment by malcolmbarrett** [comment]
I wouldn't worry too much about typos for chapters 3-4, as they'll be getting a good overhaul very soon. But content issues or clarification requests welcome

**Comment by rpruim** [comment]
How soon?  I'm starting a course next week and am planning to use this book as one of the main references.  How unstable is it likely to be?

**Comment by malcolmbarrett** [comment]
Within the next couple weeks. The structure and concepts covered will be very similar. 

We have tags at the top of every chapter that indicates the chapter's state and stability. I'm working on stabilizing the first 11 chapters to close to what they'll be on publication. Chapters 7-11 will also be getting changes but will be more copy edits and expansion than rewriting. Sorry for the timing but hello from Ann Arbor

**Comment by rpruim** [comment]
It will just make things a bit more "exciting".  I suppose I could always fork the repo and host a static copy if I wanted to ;-)

How long are you going to be in Ann Arbor?

**Comment by malcolmbarrett** [comment]
I live here and am from here! (I work remotely at Stanford). I also used to live in GR.

Yes, now that you say it, I think fork&host is how people should make our content static right now, particularly when they are depending on content that is not marked as stable
