### ISSUE TITLE
Figure out how to create nice time-aware DAGs

### ISSUE THREAD

**Issue by LucyMcGowan** [r-causal/causal-inference-in-R#32]
@malcolmbarrett I am trying to make something simple like this: 
<img width="179" alt="image" src="https://user-images.githubusercontent.com/8431897/152616012-3369f7d4-f7a6-40de-9c96-2513e6022605.png">

with ggdag but I can't seem to get one arc and one straight line 😂 is this doable? or worth it? It seems like this type of thing will be nice if we want to enforce the "time along x-axis" of a DAG rule

**Comment by malcolmbarrett** [comment]
Off the top of my head, it's possible but takes a little maneuvering: 

``` r
library(ggdag)
library(ggplot2)
p <- dagify(
  y ~ l, 
  a ~ l, 
  coords = list(x = c(l = 1, a = 2, y = 3), y = c(l = 1, a = 1, y = 1))
) %>%
  ggplot(aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_dag_point() +
  geom_dag_text() +
  theme_dag() +
  ylim(0, 2)

p + geom_dag_edges_arc(curvature = c(0, .5))
```

![](https://i.imgur.com/Q7Ci1GC.png)

<sup>Created on 2022-02-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by LucyMcGowan** [comment]
beautiful!!! I didn't think to pass curvature a vector 🤦‍♀️ what do you think about recommending this?
