### ISSUE TITLE
01.01: Description, prediction, and explanation

### ISSUE THREAD

**Issue by malcolmbarrett** [r-causal/causal-inference-in-R#57]
- [x]  A Second Chance to Get Causal Inference Right: A Classification of Data Science Tasks: https://amstat.tandfonline.com/doi/full/10.1080/09332480.2019.1579578
- [x] #53, data: https://osf.io/jtdaz/
- [x] to explain or predict (see below)
- [x] table two fallacy: https://academic.oup.com/aje/article/177/4/292/147738, https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6103824/
- [ ] mention how techniques in prediction modeling do and don't apply

# Description papers
- [ ] https://twitter.com/EpidByDesign/status/1559632956687372293
- [ ] https://twitter.com/annakporter/status/1559210713100570624
- [ ] https://twitter.com/WhitneyEpi/status/1559609155614375937
- [ ] https://twitter.com/maryaglipay/status/1559654992037961732
- [ ] https://twitter.com/Epi_D_Nique/status/1564378859205808131
- [ ] https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(09)61922-X/fulltext
- [ ] https://fn.bmj.com/content/99/5/F413
- [ ] Data journalism examples? E.g. FT COVID graphs from early in the pandemic: https://www.ft.com/content/a2901ce8-5eb7-4633-b89c-cbdf5b386938
- [ ] https://twitter.com/EpiEllie/status/1574394792414437380

# Prediction papers
- [ ] https://www.thelancet.com/journals/lanres/article/PIIS2213-2600(20)30559-2/fulltext
- [ ] https://www.bmj.com/content/369/bmj.m1328

# Causal Inference papers
- [ ] https://www.nejm.org/doi/full/10.1056/NEJMoa2211029
- [ ] https://twitter.com/_MiguelHernan/status/1559425817322700802
- [ ] https://obgyn.onlinelibrary.wiley.com/doi/10.1111/1471-0528.15659
- [ ] https://obgyn.onlinelibrary.wiley.com/doi/10.1111/1471-0528.16906
- [ ] https://www.recoverytrial.net/

## Examples provided by Scott Cunningham

- [ ] https://www.sciencedirect.com/science/article/abs/pii/S0094119010000896
- [ ] https://www.scunning.com/files/cunningham-and-finlay-2012.pdf
- [ ] https://dmarkanderson.com/ECNS432_Fall2020/JHE_MethProject.pdf
- [ ] https://www.aeaweb.org/articles?id=10.1257/pol.3.3.1
- [ ] https://academic.oup.com/qje/article-abstract/133/1/407/4060075?login=false

## RCTS
- [ ] Describe the ideal
- [ ] Discuss A/B tests
- [ ] https://www.nytimes.com/2022/09/24/business/linkedin-social-experiments.html

**Comment by tgerke** [comment]
Possible tidbit to include: here's a proof with simple `lm` showing how you can use a causally biased model to improve prediction performance (i.e. answers the question "wouldn't the best prediction model always be the precise causal model?" with the answer "no."). 

Slide 10 [here](https://overcookedmodels.netlify.app/#10) shows the relevance section from [this paper](https://www.stat.berkeley.edu/~aldous/157/Papers/shmueli.pdf)
